all:
	clang -arch arm64 cpu_print.s -o cpu_print
	./cpu_print
	echo "for other hardware components: https://chatgpt.com/share/69547a01-827c-800c-bbe4-e94f8e4cbc68"
	
# cpu:
# 	clang -arch arm64 cpu.s -o cpu
# 	
# cpu_print:	
# 	clang -arch arm64 cpu_print.s -o cpu_print