// main.c
#include <Python.h>
#include <stdlib.h>
#include <string.h>
#include "hello_py.h"  // generated by xxd -i

int main(int argc, char **argv) {
    PyStatus status;
    PyConfig config;
    PyConfig_InitPythonConfig(&config);

    // Keep it self-contained and deterministic
    config.isolated = 1;         // ignore user site, env vars, etc.
    config.use_environment = 0;  // don't read PYTHON* env

    // Program name (shows up as sys.argv[0])
    status = PyConfig_SetBytesString(&config, &config.program_name, argv[0]);
    if (PyStatus_Exception(status)) { PyConfig_Clear(&config); return 1; }

    status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) { return 1; }

    // Copy embedded script into a NUL-terminated buffer
    char *buf = (char*)malloc(hello_py_len + 1);
    if (!buf) { Py_Finalize(); return 1; }
    memcpy(buf, hello_py, hello_py_len);
    buf[hello_py_len] = '\0';

    int rc = PyRun_SimpleString(buf);  // run the script
    free(buf);

    Py_Finalize();
    return rc != 0; // nonzero means an exception occurred
}
